export enum AVAILABLE_MENU_LIST {
  MAIN = "MAIN",
  PAIRING = "PAIRING",
  VARIETIES = "VARIETIES",
  DRINKING_GUIDE = "DRINKING_GUIDE",
  INDICATION = "INDICATION",
  SCENT = "SCENT",
  ADULT = "ADULT",
  SMART_ORDER = "SMART_ORDER",
  WARNING = "WARNING",
  BRAND_SHOP_TOP = "BRAND_SHOP_TOP",
  BRAND_SHOP_BOTTOM = "BRAND_SHOP_BOTTOM",
}
